goodboicollector/urls.py
from django.contrib import admin
# Add the include function to the import
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # In this case '' represents the root route
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('goodboiz/', views.gb_index, name='index'),
    path('goodboiz/<int:gb_id>/', views.gb_detail, name='detail'),
    path('goodboiz/create/', views.GoodboiCreate.as_view(), name='gb_create'),
    path('goodboiz/<int:pk>/update/',
         views.GoodboiUpdate.as_view(), name='gb_update'),
    path('goodboiz/<int:pk>/delete/',
         views.GoodboiDelete.as_view(), name='gb_delete'),
    path('goodboiz/<int:goodboiz_id>/add_feeding/',
         views.add_feeding, name='add_feeding'),
    path('goodboiz/<int:gb_id>/assoc_toy/<int:toy_id>/',
         views.assoc_toy, name='assoc_toy'),
    path('toys/', views.ToyList.as_view(), name='toys_index'),
    path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toys_detail'),
    path('toys/create/', views.ToyCreate.as_view(), name='toys_create'),
    path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toys_update'),
    path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toys_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Toy(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('toys_detail', kwargs={'pk': self.id})


# Note that parens are optional if not inheriting from another class
class Goodboiz(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    toys = models.ManyToManyField(Toy)

    def __str__(self):
            return self.name

    def get_absolute_url(self):
            # first argument is a name of a url (looks at kwargs in urls.py)
            # self.id is referring to the id of the cat you just
            # created and or updated
        return reverse('detail', kwargs={'gb_id': self.id})


MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner'),
)


class Feeding(models.Model):
    date = models.DateField()
    meal = models.CharField(
        max_length=1,
        # this will help us make a select menu when a form is created from this model
        choices=MEALS,
        default=MEALS[0][0])

    # create a cat_id FK (Cat is our model)
    # <- If you delete cat, delete all the feeding associated with the cat as well
    goodboiz = models.ForeignKey(Goodboiz, on_delete=models.CASCADE)

    def __str__(self):
        # get_meal_display() is a method django creates for  Charfields that have choices (Select menu)
        # get_<property name>_display() -> automatically shows the humnan readable value, so if meal's value is "B", the method
        # will return Breakfast, (look at the tuple!)
        return f"{self.get_meal_display()} on {self.date}"

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

# when we instiate this class, we will create a form from our Feeding Model


class FeedingForm(ModelForm):
    # meta class, this instructions for the class
    class Meta:
        model = Feeding
        fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render, redirect
from .models import Goodboiz, Toy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .forms import FeedingForm
from django.http import HttpResponse

# Create your views here.


def add_feeding(request, goodboiz_id):
  # create a ModelForm instance using the data from the
  # post request (when our form submits from the client to server)
  # request.POST is the contents of the form, when submitted
  form = FeedingForm(request.POST)
  # validate the form
  if form.is_valid():
    # save an instance in memory
    new_feeding = form.save(commit=False)
    # new_feeding.cat_id comes from the model key on Feeding called cat
    # remember the _id is automatically appended to it
    new_feeding.goodboiz_id = goodboiz_id
    new_feeding.save()
    # we always redirect when we change data in the database
    # in this case we added a feeding to a cat
    # cat_id on the left refers to the param in url
    # cats/<int:cat_id>/' for the details
    # cat_id on the right is referring to the actually id, we
    # reusing the cat_id from form submission that is argument to add_feeding
    # function above
  return redirect('detail', gb_id=goodboiz_id)

class GoodboiCreate(CreateView):
    model = Goodboiz

    fields = ['name', 'breed', 'description', 'age']
    

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def gb_index(request):
    gb = Goodboiz.objects.all()
    return render(request, 'goodboiz/index.html', { 'gb': gb })

def gb_detail(request, gb_id):
    gb = Goodboiz.objects.get(id=gb_id)
    toys_gb_doesnt_have = Toy.objects.exclude(
        id__in=gb.toys.all().values_list('id'))
    feeding_form = FeedingForm()
    return render(request, 'goodboiz/detail.html', {'gbz': gb, 'feeding_form': feeding_form, 'toys': toys_gb_doesnt_have})

class GoodboiUpdate(UpdateView):
    model = Goodboiz

    fields = ['breed', 'description', 'age']

class GoodboiDelete(DeleteView):
    model = Goodboiz
    success_url = '/goodboiz/'


class ToyList(ListView):
    model = Toy


class ToyDetail(DetailView):
    model = Toy


class ToyCreate(CreateView):
    model = Toy
    fields = '__all__'


class ToyUpdate(UpdateView):
    model = Toy
    fields = ['name', 'color']


class ToyDelete(DeleteView):
    model = Toy
    success_url = '/toys/'


def assoc_toy(request, gb_id, toy_id):
  # Note that you can pass a toy's id instead of the whole object
  Goodboiz.objects.get(id=gb_id).toys.add(toy_id)
  return redirect('detail', gb_id=gb_id)

main_app/templates/about.html
{% extends 'base.html' %}


{% block content %}
<h1>I love goodboiz</h1>
{% endblock content %}
    

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>GoodBoi Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</head>

<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li><a href="/" class="left brand-logo">&nbsp;&nbsp;GoodBoi Collector</a></li>
                </ul>
                <ul class="right">
                    <li><a href="/about">About</a></li>
                    <li><a href="/goodboiz">GoodBoiz</a></li>
                    <li><a href="{% url 'toys_create' %}">Add a Toy</a></li>
                    <li><a href="{% url 'toys_index' %}">View All Toys</a></li>
                    <li><a href={% url 'gb_create' %}>Create Goodboi</a></li>
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="page-footer">
        <div class="right">All Rights Reserved, &copy; 2022 GoodBoi Collector &nbsp;</div>
    </footer>
</body>

</html>

main_app/templates/goodboiz/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Cat Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ gbz.name }}</span>
                <p>Breed: {{ gbz.breed }}</p>
                <p>Description: {{ gbz.description }}</p>
                {% if gbz.age > 0 %}
                <p>Age: {{ gbz.age }}</p>
                {% else %}
                <p>Age: Kitten</p>
                {% endif %}
            </div>
            <div class="card-action">
                <a href="{% url 'gb_update' gbz.id %}">Edit</a>
                <a href="{% url 'gb_delete' gbz.id %}">Delete</a>
            </div>
        </div>
    </div>

    <div class="col s6">
        <form action="{% url 'add_feeding' gbz.id %}" method="post">
            {% csrf_token %}
            {{ feeding_form.as_p }}
            <input type="submit" class="btn" value="Add Feeding">
        </form>
        <table class="striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Meal</th>
                </tr>
            </thead>
            <tbody>
                {% for feeding in gbz.feeding_set.all %}
                <tr>
                    <td>{{feeding.date}}</td>
                    <td>{{feeding.get_meal_display}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>


<hr>
<div class="row">
    <div class="col s6">
        <h3>{{ gbz.name }}'s Toys</h3>
        {% if gbz.toys.count %}
        {% for toy in gbz.toys.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
                </span>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h5>No Toys :(</h5>
        {% endif %}
    </div>
    <!-- Available toys will come after this line -->
</div>

<div class="col s6">
    <h3>Available Toys</h3>
    {% if toys.count %}
    {% for toy in toys.all %}
    <div class="card">
        <div class="card-content">
            <span class="card-title">
                A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
            </span>
        </div>
        <div class="card-action">
            <form action="{% url 'assoc_toy' gbz.id toy.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn">Add</button>
            </form>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <h5>{{gbz.name}} Already Has All Toys Available</h5>
    {% endif %}
</div>


<script>
    const selectEl = document.querySelector('#id_meal');
    M.FormSelect.init(selectEl)

    const dateEl = document.querySelector('#id_date');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    })

</script>
{% endblock %}

main_app/templates/goodboiz/index.html
{% extends 'base.html' %}


{% block content %}
<h1>GoodBoi List</h1>


{% for gbz in gb %}
<div class="card">
    <a href="/goodboiz/{{ gbz.id }}">
    <div class="card-content">
        <span class="card-title">{{ gbz.name }}</span>
        <p>Breed: {{ gbz.breed }}</p>
        <p>Description: {{ gbz.description }}</p>

        {% if gbz.age > 0 %}
        <p>Age: {{ gbz.age }}</p>
        {% else %}
        <p>Age: baby</p>

        {% endif %}

    </div>
    </a>
</div>
{% endfor %}


{% endblock content %}

main_app/templates/home.html
{% extends 'base.html' %}


{% block content %}
    <h1>GoodBoi Homepage</h1>
{% endblock content %}

main_app/templates/main_app/goodboiz_confirm_delete.html
{% extends 'base.html' %}


{% block content %}

<h1>Delete Goodboi</h1>
<h4>are you sure you want to delete {{ object.name }}</h4>

<form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes- Delete!" class="btn">
    <a href={% url 'detail' goodboiz.id %}>Cancel</a>
</form>

{% endblock content %}

main_app/templates/main_app/goodboiz_form.html
{% extends 'base.html' %} 
{% block content %}




{% if object %}
<h1>Edit {{ object.name }}</span></h1>
{% else %}
<h1>Add GoodBoi</h1>
{% endif %}

<!-- leaving the action blank makes the form submit to the same url used
to display the form -->
<form action="" method="post">
  <!-- all django forms need a cross site request forgery token  see-surf -->
  {% csrf_token %}
  <table>
    <!-- we get form for free from our CBV, form object is generated from the model!-->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>

{% endblock content %}

main_app/templates/main_app/toy_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Toy</h1>

<h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'toys_detail' object.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/toy_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Toy Details</h1>

<div class="row">
    <div class="col s6 col-offset-3">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ toy.name }}</span>
                <p>Color: {{ toy.color }}</p>
            </div>
            <div class="card-action">
                <a href="{% url 'toys_update' toy.id %}">Edit</a>
                <a href="{% url 'toys_delete' toy.id %}">Delete</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main_app/templates/main_app/toy_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Toy</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
        <!-- Render the inputs inside of <tr>s & <td>s -->
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
</form>
{% endblock %}

main_app/templates/main_app/toy_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Toy List</h1>

{% for toy in toy_list %}
<a href="{% url 'toys_detail' toy.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ toy.name }}</span>
            <p>Color: {{ toy.color }}</p>
        </div>
    </div>
</a>
{% endfor %}

{% endblock %}